// Auto-generated by scripts/gen-build-info.cjs
// Do not edit manually. Values are injected at build time.
export const BUILD_INFO = {
  commitShort: "d8a804e",
  commit: "d8a804ebbbbc091b8ae2e489e6ef0c9f98f45fac",
  builtAt: "2025-08-22T13:20:38.881Z"
} as const;
