// Auto-generated by scripts/gen-build-info.cjs
// Do not edit manually. Values are injected at build time.
export const BUILD_INFO = {
  commitShort: "9e43fe3",
  commit: "9e43fe30cb1286422a1a4e95dd79e23182182594",
  builtAt: "2025-08-22T13:14:06.667Z"
} as const;
