// Auto-generated by scripts/gen-build-info.cjs
// Do not edit manually. Values are injected at build time.
export const BUILD_INFO = {
  commitShort: "2ea680c",
  commit: "2ea680ca1b6e452ffd237ba409b90653e60cec3d",
  builtAt: "2025-08-25T14:13:56.304Z"
} as const;
