# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - framocrm-backend

on:
  # Disable automatic deployment from this legacy workflow; keep manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Only deploy the backend folder; dependencies will be installed at startup on Azure
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'framocrm-backend'
          slot-name: 'Production'
          # Deploy only the backend contents to the site root
          package: ./
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_048DD0FF498C44A78D4A52EA32064D5F }}